YEAR: year
QUARTER: quarter
MONTH: month
DAY_OF_MONTH: day_of_month
DAY_OF_WEEK: day_of_week
FL_DATE: flight_date
OP_UNIQUE_CARRIER: reporting_airline
OP_CARRIER_FL_NUM: flight_number
ORIGIN: origin
DEST: destination
CRS_DEP_TIME: crs_dep_time
DEP_TIME: dep_time
DEP_DELAY: departure_delay_minutes
CRS_ARR_TIME: crs_arr_time
ARR_TIME: arr_time
ARR_DELAY: arrival_delay_minutes
CANCELLED: cancelled
CANCELLATION_CODE: cancellation_code
DIVERTED: diverted
CRS_ELAPSED_TIME: scheduled_elapsed_minutes
ACTUAL_ELAPSED_TIME: actual_elapsed_minutes
AIR_TIME: air_time_minutes
DISTANCE: distance_miles
CARRIER_DELAY: carrier_delay_minutes
WEATHER_DELAY: weather_delay_minutes
NAS_DELAY: nas_delay_minutes
SECURITY_DELAY: security_delay_minutes
LATE_AIRCRAFT_DELAY: late_aircraft_delay_minutes

